local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint

  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 0.5  

  static_map: false  
  rolling_window: true
  width: 3
  height: 3
  resolution: 0.05

  # inflation_radius: 0.2 # 0.8 # 1.0 # 0.1
  # cost_scaling_factor: 4.0 # 3.0 # 2.5 # 2.0 # 3.0
